steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/express-app:$COMMIT_SHA", "."]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "express-app"
      - "--image"
      - "gcr.io/$PROJECT_ID/express-app:$COMMIT_SHA"
      - "--platform"
      - "managed"
      - "--region"
      - "us-central1"
      - "--allow-unauthenticated"
images:
  - "gcr.io/$PROJECT_ID/express-app:$COMMIT_SHA"
