name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main   # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.7.1
      with:
        project_id: final-project-443911
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Build Docker image
      run: |
        docker build -t gcr.io/final-project-443911/realtime-innovations-project6 .

    - name: Push Docker image to Google Container Registry
      run: |
        docker push gcr.io/final-project-443911/realtime-innovations-project6

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy realtime-innovations-project6 \
          --image gcr.io/final-project-443911/realtime-innovations-project6 \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
